### ISSUE TITLE
Wrap paths in double quotes to account for spaces in filepaths

### ISSUE THREAD

**Issue by amakvana** [PyrosStuff/A-Train#4]
```
type "txt\GPL_v3.txt"
type "txt\ascii.txt"
mkdir "Output"
```

Instead of:

```
type txt\GPL_v3.txt
type txt\ascii.txt
mkdir Output
```

It's also good habit to do this as it'll avoid path headaches when you write more complex scripts

**Comment by rlake08** [comment]
Thanks! I'm pretty new to batch and just interpreted in general, so tips like this are helpful.
